// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBto1xdCrs5Jhb6NW7I9SIZgJW14veDRSc',
    appId: '1:901839003391:web:1e0d1f4898a48af46bf6ca',
    messagingSenderId: '901839003391',
    projectId: 'gawein-3742b',
    authDomain: 'gawein-3742b.firebaseapp.com',
    storageBucket: 'gawein-3742b.firebasestorage.app',
    measurementId: 'G-R5HHXXTWD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOskenZ5QH3dEKaNY7-jhATJmk-uhjD0o',
    appId: '1:901839003391:android:7dbbdc8c37d6b9ed6bf6ca',
    messagingSenderId: '901839003391',
    projectId: 'gawein-3742b',
    storageBucket: 'gawein-3742b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtC1f_QZVyB_Hzlm6aEAeoeWkFsZ8fiFk',
    appId: '1:901839003391:ios:cdab29bbde32e2546bf6ca',
    messagingSenderId: '901839003391',
    projectId: 'gawein-3742b',
    storageBucket: 'gawein-3742b.firebasestorage.app',
    iosBundleId: 'com.example.timtujuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtC1f_QZVyB_Hzlm6aEAeoeWkFsZ8fiFk',
    appId: '1:901839003391:ios:cdab29bbde32e2546bf6ca',
    messagingSenderId: '901839003391',
    projectId: 'gawein-3742b',
    storageBucket: 'gawein-3742b.firebasestorage.app',
    iosBundleId: 'com.example.timtujuh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBto1xdCrs5Jhb6NW7I9SIZgJW14veDRSc',
    appId: '1:901839003391:web:54079db6ed3851b36bf6ca',
    messagingSenderId: '901839003391',
    projectId: 'gawein-3742b',
    authDomain: 'gawein-3742b.firebaseapp.com',
    storageBucket: 'gawein-3742b.firebasestorage.app',
    measurementId: 'G-KTSEE9X2SL',
  );

}